title: Causal Commit Flow
description: YOUR DESCRIPTION
theme: just-the-docs

url: https://sailuh.github.io/causal_commit_flow_docs

aux_links: # remove if you don't want this link to appear on your pages
  Template Repository: https://github.com/sailuh/causal_commit_flow_docs
